#pragma once
// Build facts generated by cmake/version.cmake into the build tree.
extern const char* const kFirnVersion;    // project version, e.g. "0.1.0"
extern const char* const kFirnCommit;     // short git commit, " (modified)" appended when the tree is dirty
extern const char* const kFirnBranch;
extern const char* const kFirnBuildDate;  // UTC date of the build
