#!/usr/bin/env python3
"""Write the API manual from what the program reports about itself.

    xvfb-run -a python3 scripts/gen_api_docs.py [build-dir] [--check]

Starts the app, asks it to describe itself, and writes docs/API-reference.md
and docs/api.json. Nothing here knows the actions: the manual is whatever
the program says, so it cannot fall behind the code. --check writes nothing
and fails if what is committed no longer matches, which is what CI runs.
"""
import json, os, subprocess, sys, tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import drive  # noqa: E402

ROOT = drive.ROOT
# Each test owns its socket and configuration; leave open editors alone.
_SESSION = tempfile.mkdtemp(prefix="firn-docs-")
drive.SOCK = os.path.join(_SESSION, "driver.sock")
args = [a for a in sys.argv[1:] if not a.startswith("--")]
CHECK = "--check" in sys.argv
BUILD = args[0] if args else os.path.join(ROOT, "build")
MD = os.path.join(ROOT, "docs", "API-reference.md")
JS = os.path.join(ROOT, "docs", "api.json")

GROUPS = [
    ("file", "Documents"), ("edit", "Editing"), ("view", "The view"),
    ("image", "The whole image"), ("select", "Selections"),
    ("draw", "Drawing"), ("layer", "Layers"), ("tool", "Tools and materials"), ("app", "The program itself"),
]


def describe():
    env = dict(os.environ, FIRN_DRIVE=drive.SOCK, XDG_CONFIG_HOME=_SESSION)
    env.setdefault("FIRN_WINDOW", "900x700")
    firn = drive.binary(BUILD, "app", "firn")
    if not os.path.exists(firn):
        sys.exit("no app binary at " + firn)
    drive.kill()
    log = open(os.path.join(tempfile.mkdtemp(prefix="firn-docs-"), "app.log"), "w")
    proc = subprocess.Popen([firn], env=env, stdout=log, stderr=subprocess.STDOUT, start_new_session=True)
    try:
        s = drive.connect(timeout=30.0)
        s.sendall(b"wait 30\n")
        drive.recv_line(s)
        s.sendall(b"do app.describe {}\n")
        reply = drive.recv_line(s)
        s.sendall(b"quit\n")
        s.settimeout(10.0)
        try:
            s.recv(4096)
        except OSError:
            pass
    finally:
        try:
            proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.kill()
        drive.kill()
    body = reply[3:] if reply.startswith("ok ") else reply
    if body.startswith("result "):
        body = body[7:]
    return json.loads(body)


def params_table(schema):
    props = schema.get("properties", {})
    if not props:
        return "Takes no parameters.\n"
    required = set(schema.get("required", []))
    out = ["| parameter | type | required | default | meaning |", "|---|---|---|---|---|"]
    for name, spec in props.items():
        t = spec["type"]
        if "enum" in spec:
            t += " (" + ", ".join(spec["enum"]) + ")"
        out.append("| `{}` | {} | {} | {} | {} |".format(
            name, t, "yes" if name in required else "no",
            "`{}`".format(json.dumps(spec["default"])) if "default" in spec else spec.get("x-default-description", ""),
            spec.get("description", "")))
    return "\n".join(out) + "\n"


def render(api):
    actions = sorted(api["actions"], key=lambda a: a["name"])
    lines = [
        "# The Firn API",
        "",
        "Generated by `scripts/gen_api_docs.py` from what the program reports;",
        "do not edit by hand. Every action below is the same code the matching",
        "menu item runs, so this manual and the program cannot disagree.",
        "",
        "Three ways to call these, all the same surface: `firn-cli do <name> '<json>'`,",
        "a line on the driver socket (`do <name> <json>`), or a `.PspScript` file.",
        "`docs/API.md` explains the transports; `docs/api.json` is this manual as",
        "machine-readable JSON Schema, one schema per action.",
        "",
        "Replies are JSON. Success is `{\"ok\":true}` and whatever the action returns;",
        "a refusal comes back as a message and a non-zero exit from `firn-cli`.",
        "",
        "{} actions and {} inherited command names.".format(len(actions), len(api.get("commands", []))),
        "",
    ]
    used = set()
    for prefix, title in GROUPS:
        group = [a for a in actions if a["name"].split(".")[0] == prefix]
        if not group:
            continue
        used.update(a["name"] for a in group)
        lines += ["## " + title, ""]
        for a in group:
            lines += ["### `{}`".format(a["name"]), "", a["summary"] + ".", ""]
            if a.get("detail"):
                lines += [a["detail"], ""]
            lines += ["Batch-safe: " + ("yes" if a.get("batch_safe") else "no") + ".", ""]
            lines += [params_table(a["input_schema"]), ""]
            for example in a.get("examples", []):
                lines += ["Example parameters:", "", "```json", json.dumps(example, indent=2), "```", ""]
            if any("items" in p for p in a["input_schema"].get("properties", {}).values()):
                lines += ["Full parameter schema:", "", "```json", json.dumps(a["input_schema"], indent=2), "```", ""]
    rest = [a for a in actions if a["name"] not in used]
    if rest:
        lines += ["## Other", ""]
        for a in rest:
            lines += ["### `{}`".format(a["name"]), "", a["summary"] + ".", "", params_table(a["input_schema"]), ""]

    lines += [
        "## Inherited commands",
        "",
        "Names from the program this grew out of, taking its parameter names",
        "verbatim (`docs/COMMANDS.md`). They are called the same way as the",
        "actions above. A trailing `*` marks a prefix, so `NewAdjustmentLayer*`",
        "means `NewAdjustmentLayerCurves` and its siblings.",
        "",
    ]
    cmds = api.get("commands", [])
    for i in range(0, len(cmds), 6):
        lines.append("".join("`{}`{}".format(c, "" if j == len(cmds[i:i + 6]) - 1 else ", ")
                             for j, c in enumerate(cmds[i:i + 6])) + ("," if i + 6 < len(cmds) else ""))
    lines.append("")
    lines += ["## Tools", "", "Names `tool.select` accepts:", "",
              ", ".join("`{}`".format(t) for t in api.get("tools", [])), ""]
    return "\n".join(lines)


def main():
    api = describe()
    md = render(api)
    js = json.dumps(api, indent=2, sort_keys=True) + "\n"
    if CHECK:
        stale = []
        for path, want in ((MD, md), (JS, js)):
            have = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
            if have != want:
                stale.append(os.path.relpath(path, ROOT))
        if stale:
            print("out of date: " + ", ".join(stale))
            print("run: python3 scripts/gen_api_docs.py")
            sys.exit(1)
        print("the API manual matches the program")
        return
    # UTF-8 with LF endings everywhere, or a Windows run rewrites every line.
    open(MD, "w", encoding="utf-8", newline="\n").write(md)
    open(JS, "w", encoding="utf-8", newline="\n").write(js)
    print("wrote {} ({} actions) and {}".format(os.path.relpath(MD, ROOT), len(api["actions"]), os.path.relpath(JS, ROOT)))


if __name__ == "__main__":
    main()
