# The inherited command names live as string comparisons in Script.cpp. This
# reads them out so `describe` can publish the whole callable surface
# without anyone maintaining a second list that would drift.
#
# It runs as a build step (cmake -DINPUT=... -DOUTPUT=... -P), not at
# configure time: adding a command to Script.cpp has to regenerate the list
# on the next build, or the program under a stale build directory reports a
# surface the source no longer has and the API manual check fails only in
# CI, where the configure is always fresh.
function(firn_generate_command_list source out)
  file(STRINGS "${source}" lines REGEX "name == \"[A-Za-z0-9_]+\"")
  set(names "")
  foreach(line IN LISTS lines)
    string(REGEX MATCHALL "name == \"([A-Za-z0-9_]+)\"" hits "${line}")
    foreach(hit IN LISTS hits)
      string(REGEX REPLACE "name == \"([A-Za-z0-9_]+)\"" "\\1" n "${hit}")
      list(APPEND names "${n}")
    endforeach()
  endforeach()
  file(STRINGS "${source}" prefixes REGEX "name.rfind\\(\"[A-Za-z0-9_]+\"")
  foreach(line IN LISTS prefixes)
    string(REGEX REPLACE ".*name.rfind\\(\"([A-Za-z0-9_]+)\".*" "\\1*" n "${line}")
    list(APPEND names "${n}")
  endforeach()
  list(REMOVE_DUPLICATES names)
  list(SORT names)
  set(body "")
  foreach(n IN LISTS names)
    string(APPEND body "    \"${n}\",\n")
  endforeach()
  file(WRITE "${out}"
    "// Generated by cmake/commands.cmake from Script.cpp. Do not edit.\n"
    "#pragma once\n\n"
    "inline const char* const kInheritedCommands[] = {\n${body}};\n")
endfunction()

if(CMAKE_SCRIPT_MODE_FILE AND DEFINED INPUT AND DEFINED OUTPUT)
  firn_generate_command_list("${INPUT}" "${OUTPUT}")
endif()
