# The inherited command names live as string comparisons in Script.cpp. This
# reads them out at build time so `describe` can publish the whole callable
# surface without anyone maintaining a second list that would drift.
function(firn_generate_command_list source out)
  file(STRINGS "${source}" lines REGEX "name == \"[A-Za-z0-9_]+\"")
  set(names "")
  foreach(line IN LISTS lines)
    string(REGEX MATCHALL "name == \"([A-Za-z0-9_]+)\"" hits "${line}")
    foreach(hit IN LISTS hits)
      string(REGEX REPLACE "name == \"([A-Za-z0-9_]+)\"" "\\1" n "${hit}")
      list(APPEND names "${n}")
    endforeach()
  endforeach()
  file(STRINGS "${source}" prefixes REGEX "name.rfind\\(\"[A-Za-z0-9_]+\"")
  foreach(line IN LISTS prefixes)
    string(REGEX REPLACE ".*name.rfind\\(\"([A-Za-z0-9_]+)\".*" "\\1*" n "${line}")
    list(APPEND names "${n}")
  endforeach()
  list(REMOVE_DUPLICATES names)
  list(SORT names)
  set(body "")
  foreach(n IN LISTS names)
    string(APPEND body "    \"${n}\",\n")
  endforeach()
  file(WRITE "${out}"
    "// Generated by cmake/commands.cmake from Script.cpp. Do not edit.\n"
    "#pragma once\n\n"
    "inline const char* const kInheritedCommands[] = {\n${body}};\n")
endfunction()
