# Writes a C++ source with the version, git commit and build date. Run on
# every build (see app/CMakeLists.txt); the output is only rewritten when it
# changes, so the app is not relinked needlessly.
#   cmake -DOUTPUT=... -DSOURCE_DIR=... -DVERSION=... -P version.cmake
find_package(Git QUIET)
set(COMMIT "unknown")
set(DIRTY "")
set(BRANCH "")
if(GIT_FOUND)
  execute_process(COMMAND ${GIT_EXECUTABLE} rev-parse --short=10 HEAD WORKING_DIRECTORY ${SOURCE_DIR}
                  OUTPUT_VARIABLE COMMIT OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE rc)
  if(NOT rc EQUAL 0)
    set(COMMIT "unknown")
  else()
    execute_process(COMMAND ${GIT_EXECUTABLE} diff --quiet HEAD -- . WORKING_DIRECTORY ${SOURCE_DIR} RESULT_VARIABLE dirty_rc ERROR_QUIET)
    if(NOT dirty_rc EQUAL 0)
      set(DIRTY " (modified)")
    endif()
    execute_process(COMMAND ${GIT_EXECUTABLE} rev-parse --abbrev-ref HEAD WORKING_DIRECTORY ${SOURCE_DIR}
                    OUTPUT_VARIABLE BRANCH OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
  endif()
endif()
string(TIMESTAMP BUILD_DATE "%Y-%m-%d" UTC)
set(CONTENT "// Generated by cmake/version.cmake; do not edit.
#include \"Version.h\"
const char* const kFirnVersion = \"${VERSION}\";
const char* const kFirnCommit = \"${COMMIT}${DIRTY}\";
const char* const kFirnBranch = \"${BRANCH}\";
const char* const kFirnBuildDate = \"${BUILD_DATE}\";
")
set(OLD "")
if(EXISTS ${OUTPUT})
  file(READ ${OUTPUT} OLD)
endif()
if(NOT OLD STREQUAL CONTENT)
  file(WRITE ${OUTPUT} "${CONTENT}")
endif()
